[workspace]
resolver = "2"
members = [
  "crates/actors",
  "crates/cli",
  "crates/compute",
  "crates/contract",
  "crates/eo_listener",
  "crates/messages",
  "crates/node",
  "crates/rpc",
  "crates/types",
  "crates/wallet",
]


[workspace.package]
name = "lasr"