[package]
name = "lasr_contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lasr_types = { path = "../types" }
sha3 = "0.10.8"
